### ISSUE TITLE
Rime插件无法记住输入的自造词

### ISSUE THREAD

**Issue by toddlerya** [fcitx5-android/fcitx5-android#427]
#### 摘要 / Summary

输入词库不存在的自造词，在Windows和Mac以及Linux的rime都可以记住输入的自造词，在这多次输入都无法记住自造词。

#### 截图 / Screenshots

https://github.com/fcitx5-android/fcitx5-android/assets/5418150/f884fe8b-ba23-4308-9b1b-522efff795d8

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android12，MIUI13.05
![Screenshot_2024-01-28-00-49-03-988_com.android.settings.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/5418150/a5ebfd54-faaf-4458-93c4-bb122127cf0d)

- 应用版本 / App Version: 0.0.8
![Screenshot_2024-01-28-00-50-23-235_org.fcitx.fcitx5.android.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/5418150/c07ac957-c3cd-4fb5-ad38-feab175727c7)

- 插件版本 / Plugins Version:0.0.8
![Screenshot_2024-01-28-00-50-27-947_org.fcitx.fcitx5.android.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/5418150/d5f66b2f-6437-4b54-9150-d579cb884986)

**Comment by rocka** [comment]
![Screenshot](https://github.com/fcitx5-android/fcitx5-android/assets/13914967/73ba4265-bdd1-4bc3-aed6-78573938c19b)

无法复现。建议检查 rime 数据目录的权限，手动触发 rime 部署并导出日志。

**Comment by toddlerya** [comment]
问题解决了，确实是数据目录的权限问题。之前我设置了把数据同步到了donwload目录，现在恢复默认配置好了。

有问题的配置：
```yaml
distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.4
install_time: "Sun Jan 28 09:26:07 2024"
rime_version: 1.9.0
# installation_id: "4d04634d-b761-48db-b64b-5e67e42eb487"
installation_id: Android_K30Pro
sync_dir: "/storage/emulated/0/Download/Rime"
update_time: "Sun Jan 28 09:38:20 2024"
```

正确的配置
```yaml
distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.4
install_time: "Sun Jan 28 09:26:07 2024"
rime_version: 1.9.0
installation_id: "4d04634d-b761-48db-b64b-5e67e42eb487"
# installation_id: Android_K30Pro
# sync_dir: "/storage/emulated/0/Download/Rime"
update_time: "Sun Jan 28 09:38:20 2024"
```
