### ISSUE TITLE
"语言切换键" 支持在插件内的输入法间切换

### ISSUE THREAD

**Issue by ccyybn** [fcitx5-android/fcitx5-android#475]
#### 摘要 / Summary

RIME输入法引擎 自身可以同时配置五笔，双拼，笔画这些不同的输入法，但是现在的切换方式， 只能在Fcitx配置的输入法键间切换，RIME是作为一个整体被切换了

而插件内的不同输入法，在一个三级列表里面，十分不好按，而且一共要点三次，极其不方便

#### 附加信息 / Additional Context

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/17547321-bb19-465f-920f-be2cf80851df)

**Comment by ccyybn** [comment]
上面那个 Latin Mode 好像有点不对，正常应该是在外面的和 繁简 同级的一个 中英 切换按钮，并不是在 schema_list 里的一个输入法，如果强行放进去，如果在有用户自建的英文字典输入方案的情况下，就显得非常碍事

```
schema_list:
  - schema: flypy
  - schema: radical_pinyin
  - schema: full_pinyin
  - schema: double_pinyin_flypy
```
